version: "3.8"

services:
  mongo:
    image: build  # Use the built image if you have a Dockerfile
    # OR image: mongo:latest  # Use the official image directly
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
